Main Menu with Controls in the Start!
Arsenic-ATG/Tetris pull request #44
Opened 2022-09-27 01:35 UTC by JJWesker10

Main menu with Controls at the Beginning before the player begins the game -- in accordance with the control description in the documentation.

2022-09-27 07:36 UTC, Arsenic-ATG requested changes
Unfortunately, SDL_TTF doesn't support newline character ("\n") plus `renderer::draw_text ()` uses `TTF_RenderText_Blended` behind the scenes to render text on screen, which also doesn't support text wrapping ( I am planning to fix it in future )

so currently the only way to render a newline is to call `renderer::draw_text ()` again with different co-ordinated (if you want, you can look at `renderer.hpp` or `renderer.cpp` to know more about how `draw_text ()` function works )

2022-09-27 08:24 UTC, Arsenic-ATG commented on src/game.cpp
> +            0xffffffff);
```suggestion
          coords center (p_renderer.get_width ()/2, p_renderer.get_height ()/2);

          p_renderer.draw_text("CONTROLS:",
                               coords(center.x - 150,
                                      center.y - 130),
                               0xffffffff);

          p_renderer.draw_text("LEFT/RIGHT ARROW -- Move Left/Right",
                               coords(center.x - 100,
                                      center.y - 100),
                               0xffffffff);

          p_renderer.draw_text("Z or UP ARROW -- Rotate Clockwise",
                               coords(center.x - 100,
                                      center.y - 80),
                               0xffffffff);

          p_renderer.draw_text("X or LEFT-CTRL -- Rotate Counterclockwise ",
                               coords(center.x - 100,
                                      center.y - 60),
                               0xffffffff);

          p_renderer.draw_text("SPACE -- Hard Drop",
                               coords(center.x - 100,
                                      center.y - 40),
                               0xffffffff);

          p_renderer.draw_text("DOWN ARROW -- Soft Drop",
                               coords(center.x - 100,
                                      center.y - 20),
                               0xffffffff);

          p_renderer.draw_text("P -- Pause Game",
                               coords(center.x - 100,
                                      center.y),
                               0xffffffff);

          p_renderer.draw_text("R -- Reset Game",
                               coords(center.x - 100,
                                      center.y + 20),
                               0xffffffff);

          p_renderer.draw_text("Press enter to start",
                               coords(center.x - 100,
                                      center.y + 60),
                               0xffffffff);
```

2022-09-28 10:03 UTC, Arsenic-ATG approved these changes
Thanks For contributing to the repository 🎉 🥇

2022-09-28 10:03 UTC, merged

2022-09-30 14:05 UTC, JJWesker10 commented
> Thanks For contributing to the repository 🎉 🥇

No problem! This was a good first experience for me! 😄